### ISSUE TITLE
Failed to load PE DOS header magic

### ISSUE THREAD

**Issue by Kobe-Satoru** [BSDFZ-programming-team/MalPro#4]
My program says "UNAVALIABLE PE FILE (failed to load)"
[e28b1212adc862b9041201c510b3fabd9df344fa24c74529f3dc8d945aa8df6e.zip](https://github.com/user-attachments/files/16667023/e28b1212adc862b9041201c510b3fabd9df344fa24c74529f3dc8d945aa8df6e.zip)

**Comment by LamentXU123** [comment]
Make sure your PE file is available to be analyzed

It seems like the program couldn't find the DOS header magic

I add a new case that will output 'failed to load the DOS Header magic' when this situation occurred

see commit e4d4b95
